<?php

namespace Database\Seeders;

use App\Models\MapLayer;
use Illuminate\Database\Seeder;

class MapLayerSeeder extends Seeder
{
    public function run(): void
    {
        $layers = [
            [
                'title' => 'Art Galleries',
                'slug' => 'art-galleries',
                'description' => 'A real-time, community-curated map layer of Art Galleries.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 14,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1I_T4Pgx6HgPo2NDP41e_k5eny8bnE29hHrZzl92VY1M/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTKrkaLfv4Ka30CDW0_Fu1DH1NGOWT7eWAbdQHETVqy2n7Kdv9jFKDXq-DptwHqbP65ljnPNLQMv4lr/pub?gid=0&single=true&output=csv',
                'maintainers' => [['name' => 'Walker Reed', 'github' => 'https://github.com/walkreed']],
            ],
            [
                'title' => 'Bike Racks',
                'slug' => 'bike-racks',
                'description' => 'A real-time, community-curated map layer of Bike Racks.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1mKUI91zlyjv0R21x31npeMHIhTS10KLgjZe08g6qLDI/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSpXqV48UWCKsogvCa951UhA5Bix97grIjBZOL94GAIof8xvDfrk-QJT2KTnK9BELr0jvMjXbsFCvGO/pub?gid=0&single=true&output=csv',
                'maintainers' => [
                    ['name' => 'Amy Lochridge', 'github' => 'https://github.com/ahmeloc/gville-map-layer-bike-racks'],
                    ['name' => 'Mark Hetu', 'github' => 'https://github.com/MarkHetu/'],
                ],
            ],
            [
                'title' => 'Breweries',
                'slug' => 'breweries',
                'description' => 'A community-curated map of Greenville, SC breweries, including notes for dog-friendly, food on-premises, and proximity to the Swamp Rabbit Trail.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => 'https://joinopenworks.com/maps/breweries/points.geojson',
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1sEAf3l_tBUAA0HbBVYoBbaKaTzYOA3YqfKtMP2P1fEA/edit?gid=0#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTRfRAqGYkltNKQDgeuFQ4Er5GXemXMhlPSquYVI8QvR0VYk6LNLoutVk3NtaUs09O0e_6aYBuPYvl4/pub?gid=0&single=true&output=csv',
                'maintainers' => [
                    ['name' => 'Jim Ciallella', 'github' => 'https://github.com/allella'],
                    ['name' => 'Ray Breneman'],
                    ['name' => 'JeriBeth', 'github' => 'https://github.com/sparklebunny'],
                    ['name' => 'Terry Horner', 'github' => 'https://github.com/terrhorn'],
                    ['name' => 'Lauren DeLisle', 'github' => 'https://github.com/Unicorned/'],
                ],
            ],
            [
                'title' => 'Cemeteries',
                'slug' => 'cemeteries',
                'description' => 'A real-time, community-curated map layer of Cemeteries.',
                'center_latitude' => 34.857100,
                'center_longitude' => -82.402100,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1vwLrBo6Fa34Iizj26JYOZLrPzPw5FIsAqUuGXRzgELI/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSPD7aCIxjyBdM8MHkWfoDfcr4fue4AyTGXHRVj7VyLEZjScFPx6Ei-4MfALMhYmh6amF7oGl4pT9wz/pub?gid=0&single=true&output=csv',
                'maintainers' => [
                    ['name' => 'Christine Grewcock', 'github' => 'https://github.com/ealdthryth'],
                    ['name' => 'Olga Pakhotina', 'github' => 'https://github.com/Olga-Pakhotina'],
                ],
            ],
            [
                'title' => 'City Halls',
                'slug' => 'city-halls',
                'description' => 'A real-time, community-curated map layer of City Halls.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1LnJK0H_A1cSST5LZOzdtQ5e7JBmrzIpdf9jsX27TSkk/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTJMwdt1oo-2AKqK_d8DZmpPvYxXPdmUB_J0x2GECQm6cTEdXopZE9mZmAds-GlswaltogoRzNYp3YR/pub?gid=0&single=true&output=csv',
                'maintainers' => [['name' => 'Octavia Frazile', 'github' => 'https://github.com/Ofrazzle']],
            ],
            [
                'title' => 'City Parks - Greenville',
                'slug' => 'city-parks-greenville',
                'description' => 'A community-curated map layer of city parks in Greenville, SC.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1951efVrvM3QLYgFIVAwoDCm51ckoh68pvCiHq8lI4P8/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQ-hYlKBjoMXCKPOO3g6bJJIiOsOL3Qr0Q3OmKQH_Cv6v-g3P6_gp8ltIThYNtgwW6pzYIOveFOT1vR/pub?gid=0&single=true&output=csv',
                'maintainers' => [['name' => 'James Aaron', 'github' => 'https://github.com/Jaaron0606']],
            ],
            [
                'title' => 'Community Gardens',
                'slug' => 'community-gardens',
                'description' => 'A real-time, community-curated map layer of Community Gardens.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1tkuJ219nwbgEqDzgMTBPxz49Va_natnKYUgiZhpEfwE/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vR-l37P7cL0bwRpIBML7vmwxKyE-zp3k9peCR7t0mXKQ9iF92DFiO7pmT8dwqGKR2XMc2zxx7_olyeH/pub?gid=0&single=true&output=csv',
                'maintainers' => [['name' => 'Leo Newman', 'github' => 'https://github.com/leojnewman']],
            ],
            [
                'title' => 'Co-working Spaces',
                'slug' => 'coworking-spaces',
                'description' => 'A real-time, community-curated map layer of Co-working Spaces.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 12,
                'geojson_link' => 'https://joinopenworks.com/maps/coworking-spaces/points.geojson',
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1SfQFG4iSbD8vlKzUfpgCEJmNQcUBnhgZZzlameKT4l8/edit?gid=0#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRtM2qaSOwlUKWRHLHpXAxk90W19jExJxILqF_3tq_mForyK6ne3V2GKrk-NPqedPuIuIUlqkt7DAjE/pub?gid=0&single=true&output=csv',
                'maintainers' => [
                    ['name' => 'Brett Brading', 'github' => 'https://github.com/bbrading'],
                    ['name' => 'Jim Ciallella', 'github' => 'https://github.com/allella'],
                ],
            ],
            [
                'title' => 'Dog Parks',
                'slug' => 'dog-parks',
                'description' => 'A real-time, community-curated map layer of Dog Parks.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1erYwUIJAkpzlYrWmVP3VMyJH1zvcqkzUJNoyjcmjFi8/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSRuCeQU27JewUljD1McwCo5WKRLVxCSe1OWkjYW8khCca_j-y5DeEl07DUvNj7xY4Tn8mb3zOz-6yG/pub?gid=0&single=true&output=csv',
                'maintainers' => [
                    ['name' => 'JeriBeth', 'github' => 'https://github.com/sparklebunny'],
                    ['name' => 'Sarah Bonner', 'github' => 'https://github.com/schemmelsc/dog-parks'],
                    ['name' => 'David Bonner', 'github' => 'https://github.com/bonvisuals/dog-parks'],
                ],
            ],
            [
                'title' => 'Dog-friendly Restaurants and Bars',
                'slug' => 'dog-friendly-restaurants-and-bars',
                'description' => 'A real-time, community-curated map layer of Dog-friendly Restaurants and Bars.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1erYwUIJAkpzlYrWmVP3VMyJH1zvcqkzUJNoyjcmjFi8/edit#gid=421615217',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSRuCeQU27JewUljD1McwCo5WKRLVxCSe1OWkjYW8khCca_j-y5DeEl07DUvNj7xY4Tn8mb3zOz-6yG/pub?gid=421615217&single=true&output=csv',
                'maintainers' => [
                    ['name' => 'Veronica Caruso', 'github' => 'https://github.com/carusova'],
                    ['name' => 'JeriBeth', 'github' => 'https://github.com/sparklebunny'],
                ],
            ],
            [
                'title' => 'Dog-friendly Retail Stores',
                'slug' => 'dog-friendly-retail-stores',
                'description' => 'A real-time, community-curated map layer of Dog-friendly Retail Stores.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1erYwUIJAkpzlYrWmVP3VMyJH1zvcqkzUJNoyjcmjFi8/edit#gid=630384392',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSRuCeQU27JewUljD1McwCo5WKRLVxCSe1OWkjYW8khCca_j-y5DeEl07DUvNj7xY4Tn8mb3zOz-6yG/pub?gid=630384392&single=true&output=csv',
                'maintainers' => [
                    ['name' => 'JeriBeth', 'github' => 'https://github.com/sparklebunny'],
                    ['name' => 'Cassandra Aiken', 'github' => 'https://github.com/cacoding/'],
                ],
            ],
            [
                'title' => 'Electric Vehicle Charging Stations',
                'slug' => 'electric-vehicle-charging-stations',
                'description' => 'A real-time, community-curated map layer of Electric Vehicle Charging Stations.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/13I5AzQt3L_QlFz4w8Z286OczId5IKBk6Bm56MpBAWO0/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRZq5Fhtp7HJI9AKzaX9gZHGpfL3x4jyABYh94CP-4_0l3aJhLuPuTlYpkHdVUxCSRWgZGD7PrB6eGe/pub?gid=0&single=true&output=csv',
                'maintainers' => [
                    ['name' => 'Stephen Silkowski', 'github' => 'https://github.com/ses29680'],
                    ['name' => 'Bob Greene', 'github' => 'https://github.com/nine6era'],
                    ['name' => 'Code For Greenville', 'url' => 'http://codeforgreenville.org'],
                ],
            ],
            [
                'title' => 'Farmers Markets',
                'slug' => 'farmers-markets',
                'description' => 'A real-time, community-curated map layer of Farmers Markets.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1ab-CYPb7XbvAw_QXmxOLSyc8iM2jinheuZpqC_jfXpw/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vReyGh7f77-BWo40hMH-xvfXy1nVXCCtsVnc0zQqecj3AMy-rjMEjL0FLmkNL9lkY94i3v3--QQrtYg/pub?gid=0&single=true&output=csv',
                'maintainers' => [
                    ['name' => 'Victoria Zambrano', 'github' => 'https://github.com/vzambrano98'],
                    ['name' => 'Eugene McGrath', 'github' => 'https://github.com/cplklegg/'],
                ],
            ],
            [
                'title' => 'Fishing Access Sites',
                'slug' => 'fishing-access-sites',
                'description' => 'A real-time, community-curated map layer of Fishing Access Sites.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1-IM5QWsYCHv7Lm2y4yEHUbo3BfBKVPEpFor6g7t1V4M/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vT0cYu9iDFj0VCVlRcl1L8oqGjKyYF-WOtxzkdi8Y0a5UWgSNJBicnRriEPoJPTSoww_4m-kQmapO_5/pub?gid=0&single=true&output=csv',
                'maintainers' => [
                    ['name' => 'Chris Sweeney', 'github' => 'https://github.com/sweenz'],
                    ['name' => 'Samantha Ng', 'github' => 'https://github.com/Sln218/'],
                ],
            ],
            [
                'title' => 'Free Job Training Resources',
                'slug' => 'free-job-training-resources',
                'description' => 'A real-time, community-curated map layer of Free Job Training Resources.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/14EGsgKzfnp4pJ4BBGgBrwWkt8dyTHhdOtvD4KanhOG8/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRuK2MSpV7GOGDHNO8VQolPATv0iP52JVBnGwm8A5MHtyq2lGb14V89ax1Gstk6k9EZhbwL9dU36hMM/pub?gid=0&single=true&output=csv',
                'maintainers' => [['name' => 'Liz Meeker Murphy', 'github' => 'https://github.com/lizziemeeker']],
            ],
            [
                'title' => 'Free Wi-Fi Hotspots',
                'slug' => 'free-wi-fi-hotspots',
                'description' => 'A real-time, community-curated map layer of Free Wi-Fi Hotspots.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => 'https://joinopenworks.com/wifi/guest-wi-fi-google-spreadsheet-to-geojson.php',
                'contribute_link' => 'https://joinopenworks.com/r/wifi',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vT4s0ss1d8wIgvge2C47n150yCa73gclQJaP4DUCyDaFCj1WNabX3Pb76Vc8kZLtvngWux4c8iyM7Ql/pub?gid=0&single=true&output=csv',
                'maintainers' => [['name' => 'OpenWorks / Jim Ciallella', 'github' => 'https://github.com/allella']],
            ],
            [
                'title' => 'Greer Public Parking',
                'slug' => 'greer-public-parking',
                'description' => 'A real-time, community-curated map layer of Greer Public Parking.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1dyXOqN3Lx29eMIXTHcN0rnRgQLR-uSOuZ6TXUUPsCtM/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQfiXdP11XZjgsOAYbl3I3fq81AcKbNQ12Wqt5aYIO5FkZNG0SyLP8-MYKvHGKUAKoSPbkbaAXQ3QBt/pub?gid=0&single=true&output=csv',
                'maintainers' => [['name' => 'Kyle Mensing', 'github' => 'https://github.com/ktmensing']],
            ],
            [
                'title' => 'Historic Sites (excluding Mills)',
                'slug' => 'historic-sites',
                'description' => 'A real-time, community-curated map layer of Historic Sites (excluding Mills).',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/13MXqtFxOpuRAuXp5yBFgezarV0S8eQ01Kbs2Ed_rtjE/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQ3USDKomUZ8eTvIAE88UauZLuIIden2SvOOx2OiZNy0qCFCe29El7p6ElXp9H_ZfxhsoLDutziM1bv/pub?gid=0&single=true&output=csv',
                'maintainers' => [
                    ['name' => 'Sarah Funk', 'github' => 'https://github.com/sfunk3'],
                    ['name' => 'Daniel Burgess', 'github' => 'https://github.com/everydaynerd'],
                    ['name' => 'Code For Greenville', 'url' => 'http://www.codeforgreenville.org'],
                    ['name' => 'Shanna Raines', 'github' => 'https://github.com/sraines'],
                ],
            ],
            [
                'title' => 'Historical African-American Churches',
                'slug' => 'historical-african-american-churches',
                'description' => 'A real-time, community-curated map layer of Historical African-American Churches.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1EBFOV7jx0iHirLFERo84nX3D4FQeG5_xcvx6yjvAWug/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQjfeINfoDjUsQjiXuEOXPctuwbj_yKMn08gbti8KxmlMEBFquIMH3aiFwNM8rl1N5cMmgNb3FNyNhp/pub?gid=0&single=true&output=csv',
                'maintainers' => [['name' => 'Justin Lewis', 'github' => 'https://github.com/jlew1914']],
            ],
            [
                'title' => 'Libraries',
                'slug' => 'libraries',
                'description' => 'A real-time, community-curated map layer of Libraries.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1iy0ObdJWiJZl1CzII_9nXL_7YyRtz0mIxiOvKUKxJ-E/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQKmOXURwyZ8dCdRYMix8h3PItdjwDSDfSI__9uxAMQXXt0uIakY3GWmRNqDj7uNHdLAoY7DBLTtiyK/pub?gid=0&single=true&output=csv',
                'maintainers' => [
                    ['name' => 'Bridgette Jefferson', 'github' => 'https://github.com/Brenascia'],
                    ['name' => 'Christine Grewcock', 'github' => 'https://github.com/ealdthryth'],
                    ['name' => 'Melody Ng', 'github' => 'https://github.com/melodyjng/'],
                ],
            ],
            [
                'title' => 'Live Theatres',
                'slug' => 'live-theatres',
                'description' => 'A real-time, community-curated map layer of Live Theatres.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1Ta34foucT758H2YxjgQrmvLh5GycqfPhyAVVztObO-o/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vT3UCXb_AWBzugzsiDROwLx5fMfGZOAc9b-3crH6PsVd86cOaEJg_QTD1-skkg4Oy83A8CD5SFwdTvc/pub?gid=0&single=true&output=csv',
                'maintainers' => [
                    ['name' => 'Stephen Hill', 'github' => 'https://github.com/thathillboy'],
                    ['name' => 'Eric Gosnell', 'github' => 'https://github.com/theklopex'],
                ],
            ],
            [
                'title' => 'Mice on Main',
                'slug' => 'mice-on-main',
                'description' => 'A real-time, community-curated map layer of Mice on Main.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1tPNBu79UyIv-MablYqt5y1sBv-x8Fg-3i3zH_BUJQz8/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vT32YJ7MwtDvSOPfPUordCxPA89Gej3rOL6QIiyBDotcNlSAztBFgoSjib0a4QylfDJ0AChirtvHtUB/pub?gid=0&single=true&output=csv',
                'maintainers' => [['name' => 'Creighton Magoun', 'github' => 'https://github.com/magoun']],
            ],
            [
                'title' => 'Music Venues',
                'slug' => 'music-venues',
                'description' => 'View and contribute to the real-time, community-curated map layer of music venues in Greenville South Carolina.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/17PUucZ1jPej4WGSlVzsLtvTJ1e8hz3KliAuQx84bdqc/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTMJ8himJKPyyM00Vvhdp8na3kFgIrjS3qVhWcUCQNPMFqOTZJKjSiBP3K2pw3qnBn7_Lh42NaaiyCF/pub?gid=0&single=true&output=csv',
                'maintainers' => [
                    ['name' => 'Julie Brett', 'github' => 'https://github.com/Juicysmo'],
                    ['name' => 'Jeremiah Adkins', 'github' => 'https://github.com/jeremiahadkins/'],
                ],
            ],
            [
                'title' => 'Organic Farms',
                'slug' => 'organic-farms',
                'description' => 'A real-time, community-curated map layer of Organic Farms.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1lFl4bfBdm7BrTMaGlpDab3OSILXw2MJhgqAhEVrNwpY/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRc_qf5ZlCcEKOPJW7x72TUaaYBIepGJQKPCb44CuqYTlzaLjVKpYjoBrsWqFkgOr1FzX2ZFxEQgjMu/pub?gid=0&single=true&output=csv',
                'maintainers' => [
                    ['name' => 'Shelby Cohen', 'github' => 'https://github.com/shelbymcohen'],
                    ['name' => 'Greg Bopp', 'github' => 'https://github.com/GBClemson/'],
                    ['name' => 'Shradha Gupta', 'github' => 'https://github.com/artshra/'],
                ],
            ],
            [
                'title' => 'Parking Decks',
                'slug' => 'parking-decks',
                'description' => 'A real-time, community-curated map layer of Parking Decks.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1NGeKFnA7QilhqoILsbXAZL5r_cGoRWUmAUh4cudrCLk/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vR6uddn7ajALJF5gCTZgfjXor1tJzHco9_dEhR1D9w5kpaj9oAe_yQaQtWcyaKm1Asrim2XNzWsF-jf/pub?gid=0&single=true&output=csv',
                'maintainers' => [['name' => 'Bethany Winston', 'github' => 'https://github.com/BethanyWinston']],
            ],
            [
                'title' => 'Playgrounds',
                'slug' => 'playgrounds',
                'description' => 'A real-time, community-curated map layer of Playgrounds.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1RzZv0V3E-FZ9zcNLJUdQOvy3MJ54iFPLG1G1ThIFIgA/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRqa_Q3-vPOosnRdTAp031dspfdDDayptTwWuYPoeTxG5UGJYv0DCsOotsMk9_m47GVeR6HxFeGFJvS/pub?gid=0&single=true&output=csv',
                'maintainers' => [['name' => 'Jisha Govindan', 'github' => 'https://github.com/jishaaa']],
            ],
            [
                'title' => 'Recreation Baseball Fields',
                'slug' => 'recreation-baseball-fields',
                'description' => 'A real-time, community-curated map layer of Recreation Baseball Fields.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1fymQgEOv3wL97wavbUDRiTBJcN7smUl95KZmSw_D4oE/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSxdswfBgwRrjF_3QZKWtdBlwaaXSq-qfI-grVXh8ueVGquaFVbWy94AbQzAbZVMonKwzYBcnZGABmG/pub?gid=0&single=true&output=csv',
                'maintainers' => [
                    ['name' => 'Katie Dowis', 'github' => 'https://github.com/ksiwod'],
                    ['name' => 'Jami Mercer', 'github' => 'https://github.com/mercergirl1'],
                ],
            ],
            [
                'title' => 'Recycling Locations',
                'slug' => 'recycling-locations',
                'description' => 'A community-curated map layer of recycling locations in downtown Greenville and Greenville County, SC.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 11,
                'geojson_link' => null,
                'contribute_link' => null,
                'raw_data_link' => 'https://www.gcgis.org/arcgis/rest/services/imap/imap/MapServer/72',
                'maintainers' => [['name' => 'Greenville County GIS API - iMAP', 'url' => 'https://www.gcgis.org/arcgis/rest/services']],
            ],
            [
                'title' => 'Schools - Greenville County',
                'slug' => 'schools-greenville-county',
                'description' => 'A real-time, community-curated map layer of Schools - Greenville County.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => null,
                'raw_data_link' => 'https://www.gcgis.org/arcgis/rest/services/imap/imap/MapServer/15',
                'maintainers' => [['name' => 'Greenville County GIS API - iMAP', 'url' => 'https://www.gcgis.org/arcgis/rest/services']],
            ],
            [
                'title' => 'Schools - Public International Baccalaureate Schools K-12',
                'slug' => 'schools-ib-k12',
                'description' => 'A real-time, community-curated map layer of Schools - Public International Baccalaureate Schools K-12.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1AMQRta_QrSBpDFVoBxbiQNMAWOr_BuNEOmvic2RTzwo/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTI_TZ46FEZ5VRNwgz6LKCs8M6UCUpx9R9qDD9GryKfKVcBTPjdS0ABcqYGYzU96Af0rnHJ8RdEUdhh/pub?gid=0&single=true&output=csv',
                'maintainers' => [['name' => 'Meenakshi Radhakrishnan', 'github' => 'https://github.com/meenasrik']],
            ],
            [
                'title' => 'Solid Waste',
                'slug' => 'solid-waste',
                'description' => 'A real-time, community-curated map layer of Solid Waste.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1I4K4lQqYG6-0DZmPRzhTXVW3UkK0TY9u5SuhdSsOEuk/edit#gid=0',
                'raw_data_link' => null,
                'maintainers' => [['name' => 'Greenville County GIS API - iMAP', 'url' => 'https://www.gcgis.org/arcgis/rest/services']],
            ],
            [
                'title' => 'Swamp Rabbit Trail - Entrances',
                'slug' => 'swamp-rabbit-trail-entrances',
                'description' => 'A real-time, community-curated map layer of Swamp Rabbit Trail - Entrances.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1TMAJJ9cwGPWWu66UN463_f-qYFudPJTjhd8LA6AMZro/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQ683u_VN6s1pAXFn_f6To_nGM2fFZyqts4Vcr0eqxteO6oYEs82P8xQPzB9tPUEfhldwN-G92Am6hz/pub?gid=0&single=true&output=csv',
                'maintainers' => [['name' => 'Levi Monday', 'github' => 'https://github.com/levimonday']],
            ],
            [
                'title' => 'Swamp Rabbit Trail - Main Path',
                'slug' => 'swamp-rabbit-trail-path',
                'description' => 'A real-time, community-curated map layer of Swamp Rabbit Trail - Main Path.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => null,
                'raw_data_link' => 'https://greenvilleopenmap.info/SwampRabbitWays.geojson',
                'maintainers' => [
                    ['name' => 'Mike Nice', 'url' => 'https://greenvilleopenmap.info'],
                    ['name' => 'OpenStreetMap Contributors', 'url' => 'https://www.openstreetmap.org'],
                ],
            ],
            [
                'title' => 'Swamp Rabbit Trail - Mile Markers',
                'slug' => 'swamp-rabbit-trail-mile-markers',
                'description' => 'A real-time, community-curated map layer of Swamp Rabbit Trail - Mile Markers.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/11JO7kbN0IDqjBtjE_flH9_T1sknzhUxwLgNXrBk-qEI/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQdPyKu69tItHHsmA-M4kcNzLTdnFJhzV4LFw-PEetmbbMEvVvHfFiwVzTT45t7-DrQxswrd9ktIUxF/pub?gid=0&single=true&output=csv',
                'maintainers' => [['name' => 'Christina Cornell', 'github' => 'https://github.com/cdhorn515']],
            ],
            [
                'title' => 'Swamp Rabbit Trail - Parking',
                'slug' => 'swamp-rabbit-trail-parking',
                'description' => 'A real-time, community-curated map layer of Swamp Rabbit Trail - Parking.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1a8HHDBMiA7YNIKkCbaIYFMpWCuC1RxiI6uNxvS8uwc0/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQ9QGNxIXubcItoY5CWakoD0IrFO1p2SuXztSLcvoTT1xMiKivQl321vMEn8OD4xoDfnTzNABVu92ZY/pub?gid=0&single=true&output=csv',
                'maintainers' => [['name' => 'Leland James', 'github' => 'https://github.com/FeroSoldato']],
            ],
            [
                'title' => 'Swamp Rabbit Trail - Water Fountains',
                'slug' => 'swamp-rabbit-trail-water-fountains',
                'description' => 'A community-curated map layer of water fountains along the Swamp Rabbit Trail in Greenville, SC.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1AiJo2DCtXnq9DlbgECUBuLFo3k2C7jIknzJSAD6w7Ds/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTaUgIjHCaEvsKai8xzUN3WdRn1AHNKkwiIsPhUOLfbxuj60o-x1n5_QSV6ZiDn7N2z469ICUET5PFr/pub?gid=0&single=true&output=csv',
                'maintainers' => [
                    ['name' => 'Caleb McQuaid', 'github' => 'https://github.com/calebmcquaid'],
                    ['name' => 'Andrew Bieber', 'github' => 'https://github.com/Andr3wB/'],
                ],
            ],
            [
                'title' => 'Swinging Benches/Benches in Falls Park',
                'slug' => 'falls-park-benches',
                'description' => 'A real-time, community-curated map layer of Swinging Benches/Benches in Falls Park.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 15,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1Ip0bS8vgE4S91YSVJ_8zyxprU9JJjckTomyNl1fjJiI/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRf-qRQW7JsYSme6KNzBcDzbjsOvHu-C07YrBw8QAiS2hGPAmUPIF8NYEYwlcAkbYbrPyHcSE1SKhEZ/pub?gid=0&single=true&output=csv',
                'maintainers' => [['name' => 'Stephen Bennett', 'github' => 'https://github.com/EdensLamb']],
            ],
            [
                'title' => 'Tent Campsites',
                'slug' => 'tent-camping',
                'description' => 'A real-time, community-curated map layer of Tent Campsites.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 7,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1rhpHqZwYDJnc9gmluM-D_He4lPgLSLfXKE2dWSO86qM/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vR5m7nqVqzj5GIECDEk6o0CaokxIMFTdQRe0JJj9-UpgjOWvpmODEW8IyZLZciINoTIQR4gH49wb50c/pub?gid=0&single=true&output=csv',
                'maintainers' => [
                    ['name' => 'Holly Vanderwal', 'github' => 'https://github.com/hollyv04'],
                    ['name' => 'Taylor Garrison', 'github' => 'https://github.com/garrison44/'],
                    ['name' => 'Matt Harvey', 'github' => 'https://github.com/MattAHarvey/'],
                ],
            ],
            [
                'title' => 'Textile Mills, Past and Present',
                'slug' => 'historic-textile-mills',
                'description' => 'A real-time, community-curated map layer of Textile Mills, Past and Present.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1iJNAcWyBYDKaNIb9Xla0z3jVSP7syAVeNgISGyIv6bo/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQDtQgs5j5xOSqCFhpgO8TFNrRt3nBMs2BBhZ2-iR75OpnSOSB2TTnq7LGVzJMTF96w2TajYKpEp12I/pub?gid=0&single=true&output=csv',
                'maintainers' => [
                    ['name' => 'David Galloway', 'github' => 'https://github.com/davidgalloway'],
                    ['name' => 'Jim Ciallella', 'github' => 'https://github.com/allella'],
                ],
            ],
            [
                'title' => 'Tree Planting Sites',
                'slug' => 'tree-planting-sites',
                'description' => 'A real-time, community-curated map layer of Tree Planting Sites.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1NfD6eZNs_tPJ3C69Eh9UaPSCebJ_n392ncDDf6U84e4/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/1NfD6eZNs_tPJ3C69Eh9UaPSCebJ_n392ncDDf6U84e4/pub?output=csv',
                'maintainers' => [
                    ['name' => 'TreesUpstate', 'url' => 'http://www.treesupstate.org'],
                    ['name' => 'Jim Ciallella', 'github' => 'https://github.com/allella'],
                ],
            ],
            [
                'title' => 'Walking Trails',
                'slug' => 'walking-trails',
                'description' => 'A real-time, community-curated map layer of Walking Trails.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1AgMhG8WcG6owi3_4Hyy0IsxYtzKeqnPtZeaMx4ZMQS4/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vR3pRuBnTdMvKXa2VR9F75To3hsRwdA_Cx3TW83iSpBYGfA_b0U9acmymfJt9SNKyJWnDRtoNCh7LwB/pub?gid=0&single=true&output=csv',
                'maintainers' => [['name' => 'Jen Robert', 'github' => 'https://github.com/jenrobert']],
            ],
            [
                'title' => 'Wall Murals',
                'slug' => 'wall-murals',
                'description' => 'A real-time, community-curated map layer of Wall Murals.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1qId9FbjK5gQ71QVbLO705EBAigJn6rrg61i6Ho3GnJg/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSIjT2SDpW4RHbG4eGWp0HGoAhhQQzQDyMNXMBSGFfSJG4WUCqi7JzgRY3mRKQB4rAduv7rKBZW3QsE/pub?gid=0&single=true&output=csv',
                'maintainers' => [['name' => 'Kristen Barbour', 'github' => 'https://github.com/kbarbs']],
            ],
            [
                'title' => 'Waterfalls',
                'slug' => 'waterfalls',
                'description' => 'A real-time, community-curated map layer of Waterfalls.',
                'center_latitude' => 34.850700,
                'center_longitude' => -82.398500,
                'zoom_level' => 10,
                'geojson_link' => null,
                'contribute_link' => 'https://docs.google.com/spreadsheets/d/1AZZeCh1tFc5-Lr80h60MuHqQ9uNmz5nKjWyiooEl7ik/edit#gid=0',
                'raw_data_link' => 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSJK9CEVdHXUe5Y-efjZkwT1PLUMJSFkcL8I9EdiE7qTULxY2-fGECa3fBKwtabIcl2oPz5SgmJqIls/pub?gid=0&single=true&output=csv',
                'maintainers' => [['name' => 'Tracy Gohs', 'github' => 'https://github.com/tlgohs']],
            ],
        ];

        foreach ($layers as $layer) {
            MapLayer::updateOrCreate(
                ['slug' => $layer['slug']],
                $layer,
            );
        }
    }
}
