version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    versioning-strategy: lockfile-only
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    versioning-strategy: lockfile-only
