name: Update API Documentation

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]
    branches:
      - master
      - develop
    paths:
        - 'app-modules/api/**'
        - 'config/scribe.php'
        - 'scribe.php'

jobs:
  update-docs:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: hackgreenville
          MYSQL_USER: hackgreenville
          MYSQL_ROOT_PASSWORD: test
          MYSQL_PASSWORD: test
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: :php_psr

      - name: install php dependencies
        run: composer install
    
      - name: install node dependencies
        run: yarn install

      - name: copy environment variables to .env
        run: cp .env.ci .env

      - name: Set Laravel app key
        run: php artisan key:generate

      - name: Generate API Docs
        run: php artisan scribe:generate

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Stage changes
          git add public/vendor/ resources/views/

          # Check if there are any changes to commit
          if ! git diff --cached --quiet; then
            git commit -m "Update API docs via GitHub Actions"
            git push
          fi